TpIntegrador/Controllers/AdminController.cs
using AyudandoAlProjimo.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TpIntegrador.Filters;
using AyudandoAlProjimo.Data;

namespace TpIntegrador.Controllers
{
    [CheckAdmin]
    public class AdminController : Controller
    {
        Entities ctx = new Entities();

        AdminService adminService = new AdminService();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Complaints()
        {
            return View(adminService.ListarDenuncias());
        }

        [HttpGet]
        public ActionResult DesestimarDenuncia(int id)
        {
            adminService.DesestimarDenuncia(id);
            return Redirect("/Admin/Complaints");
        }

        [HttpGet]
        public ActionResult AceptarDenuncia(int id)
        {
            adminService.AceptarDenuncia(id);
            return Redirect("/Admin/Complaints");
        }

        //[HttpGet]
        //public ActionResult DetalleDenuncia(int id)
        //{

        //}
    }

}

TpIntegrador/Controllers/DonacionesController.cs
using AyudandoAlProjimo.Data;
using AyudandoAlProjimo.Data.ViewModels;
using AyudandoAlProjimo.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TpIntegrador.Filters;
using TpIntegrador.Utilities;

namespace TpIntegrador.Controllers
{
    public class DonacionesController : Controller
    {
        private ProposalService ProposalService = new ProposalService();

        [CheckSession]
        public ActionResult Index(int id)
        {
            var p = ProposalService.BuscarPorId(id);

            switch (p.TipoDonacion)
            {
                case (int)TipoPropuestaEnum.Monetaria:
                    return Redirect("/Donaciones/DonarMonetario/" + id);
                case (int)TipoPropuestaEnum.Insumos:
                    return Redirect("/Donaciones/DonarInsumos/" + id);
                case (int)TipoPropuestaEnum.HorasTrabajo:
                    return Redirect("/Donaciones/DonarHoras/" + id);
            }

            return View();
        }

        [CheckSession]
        public ActionResult DonarInsumos(int id)
        {
            RealizarDonacionInsumosViewModel m = new RealizarDonacionInsumosViewModel();
            m.Propuesta = ProposalService.BuscarPorId(id);
            m.Formulario = new RealizarDonacionInsumosFormulario();
            m.Formulario.Insumos = new List<InsumosViewModel>();
            foreach (var item in m.Propuesta.PropuestasDonacionesInsumos)
            {
                m.Formulario.Insumos.Add(new InsumosViewModel() { Id = item.IdPropuestaDonacionInsumo, Cantidad = 0, Nombre = item.Nombre });
            }

            return View(m);
        }

        [CheckSession]
        public ActionResult DonarMonetario(int id)
        {
            RealizarDonacionMonetariaViewModel m = new RealizarDonacionMonetariaViewModel();
            m.Formulario = new RealizarDonacionMonetariaFormulario();
            m.Propuesta = ProposalService.BuscarPorId(id);

            return View(m);
        }

        [CheckSession]
        public ActionResult DonarHoras(int id)
        {
            RealizarDonacionHorasViewModel m = new RealizarDonacionHorasViewModel();
            m.Formulario = new RealizarDonacionHorasFormulario();
            m.Propuesta = ProposalService.BuscarPorId(id);

            return View(m);
        }

        [CheckSession]
        public ActionResult MisDonaciones()
        {
            ViewBag.SessionID = Session["ID"];
            return View();
        }

        [HttpPost]
        public ActionResult DonarMonetario(RealizarDonacionMonetariaViewModel m)
        {
            int id = Int32.Parse(RouteData.Values["id"].ToString());
            m.Propuesta = ProposalService.BuscarPorId(id);

            if (!ModelState.IsValid) return View(m);

            var name = m.Propuesta.Nombre + "-" + Session["ID"];
            m.Formulario.ArchivoTransferencia = GetPathForPhoto(name);

            ProposalService.AgregarDonacionMonetaria(m.Formulario, (int)Session["ID"], id);

            return Redirect("/Home/Index");
        }

        [HttpPost]
        public ActionResult DonarHoras(RealizarDonacionHorasViewModel m)
        {
            int id = Int32.Parse(RouteData.Values["id"].ToString());
            m.Propuesta = ProposalService.BuscarPorId(id);

            if (!ModelState.IsValid) return View(m);

            ProposalService.AgregarDonacionHoras(m.Formulario, (int)Session["ID"], id);

            return Redirect("/Home/Index");
        }

        [HttpPost]
        public ActionResult DonarInsumos(RealizarDonacionInsumosViewModel m)
        {
            int id = Int32.Parse(RouteData.Values["id"].ToString());
            m.Propuesta = ProposalService.BuscarPorId(id);

            if (!ModelState.IsValid) return View(m);

            ProposalService.AgregarDonacionInsumos(m.Formulario, (int)Session["ID"], id);

            return Redirect("/Home/Index");
        }

        private string GetPathForPhoto(string name)
        {
            return ImagenesUtility.Guardar(Request.Files[0], name + "-FOTO");
        }
    }
}

TpIntegrador/Controllers/IngresarController.cs
using AyudandoAlProjimo.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AyudandoAlProjimo.Services;
using AyudandoAlProjimo.Data;

namespace TpIntegrador.Controllers
{
    public class IngresarController : Controller
    {

        LoginService loginService = new LoginService();

        [HttpGet]
        public ActionResult Login()
        {
            LoginViewModel loginViewModel = new LoginViewModel();
            return View(loginViewModel);
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel loginViewModel)
        {
            if (ModelState.IsValid)
            {
                Usuarios user = loginService.VerifyUser(loginViewModel);

                if (user != null)
                {
                    Session["ID"] = user.IdUsuario;
                    Session["UserNombre"] = user.Email;
                    Session["User"] = user.TipoUsuario;
                    HttpCookie returnCookie = Request.Cookies["returnUrl"];
                    if ((returnCookie == null) || string.IsNullOrEmpty(returnCookie.Value))
                    {
                        return Redirect("/Home/Index");
                    }
                    else
                    {
                        HttpCookie deleteCookie = new HttpCookie("returnUrl");
                        deleteCookie.Expires = DateTime.Now.AddDays(-1);
                        Response.Cookies.Add(deleteCookie);
                        Response.Redirect(returnCookie.Value);
                    }
                }
                else
                {
                    TempData["message"] = "Wrong Email or Password";
                    return View(loginViewModel);
                }
            }
            return View(loginViewModel);
        }
		
        public ActionResult Logout()
        {
            Session.Abandon(); // it will clear the session at the end of request
            return RedirectToAction("Index", "Home");
        }

        //[HttpGet]
        //public ActionResult Logout()
        //{
        //    /*
        //       Session.Remove("IdRolPermiso");
        //       Session("IdRolPermiso") = null;
        //     */
        //    Session["ID"] = null;
        //    Session["User"] = null;

        //    return Redirect("/Home/Index");
        //}
    }
}

TpIntegrador/Controllers/PerfilController.cs
using System.Web.Mvc;
using AyudandoAlProjimo.Data.ViewModels;
using AyudandoAlProjimo.Services;
using AyudandoAlProjimo.Data;
using TpIntegrador.Utilities;
using TpIntegrador.Filters;

namespace TpIntegrador.Controllers
{
    public class PerfilController : Controller
    {
        private readonly UserService us = new UserService();

        [CheckUser]
        [HttpGet]
        public ActionResult Index()
        {
            var user = us.TraerPerfilDelUsuario((int)Session["ID"]);

            var ViewModel = new PerfilViewModel();

            ViewModel.Nombre = user.Nombre;
            ViewModel.Apellido = user.Apellido;
            ViewModel.FechaNacimiento = user.FechaNacimiento;
            ViewModel.Foto = user.Foto;
            ViewModel.Email = user.Email;
            ViewModel.UserName = user.UserName;

            return View(ViewModel);
        }

        [HttpPost]
        public ActionResult Index(PerfilViewModel pvm)
        {
            if (!ModelState.IsValid) return View(pvm);

            Usuarios usuarioBD = us.TraerPerfilDelUsuario((int)Session["ID"]);
            if (Request.Files.Count > 0 && Request.Files[0].ContentLength > 0)
            {
                //TODO: Agregar validacion para confirmar que el archivo es una imagen
                if (!string.IsNullOrEmpty(pvm.Foto))
                {
                    //recordar eliminar la foto anterior si tenia
                    if (!string.IsNullOrEmpty(usuarioBD.Foto))
                    {
                        ImagenesUtility.Borrar(usuarioBD.Foto);
                    }

                    //creo un nombre significativo en este caso apellidonombre pero solo un caracter del nombre, ejemplo BatistutaG
                    string nombreSignificativo = pvm.Nombre + pvm.Apellido;
                    //Guardar Imagen
                    string pathRelativoImagen = ImagenesUtility.Guardar(Request.Files[0], nombreSignificativo);
                    usuarioBD.Foto = pathRelativoImagen;
                }
            }

            usuarioBD.Nombre = pvm.Nombre;
            usuarioBD.Apellido = pvm.Apellido;
            usuarioBD.FechaNacimiento = pvm.FechaNacimiento;
            us.ActualizarPerfilDelUsuario(usuarioBD);

            return Redirect("/Home/Index");
        }
    }
}

TpIntegrador/Views/Shared/AnonimoLayout.cshtml
@{
    Layout = "~/Views/Shared/BaseLayout.cshtml";
}

<main>
    @RenderBody()
</main>


@Html.Partial("pv_Footer")

TpIntegrador/Views/Shared/BaseLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Ayudando al projimo</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" id="et-builder-googlefonts-cached-css" href="https://fonts.googleapis.com/css?family=Oswald%3A200%2C300%2Cregular%2C500%2C600%2C700%7CPlayfair+Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic&amp;ver=4.9.12#038;subset=cyrillic,vietnamese,latin,latin-ext" type="text/css" media="all">

    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="teal fixed-top-navbar">
        <div class="container container-top-navbar">
            @if (Session["ID"] == null)
            {
                @Html.ActionLink("Login", "Login", "Ingresar", null, new { @class = "white-text waves-effect waves-teal btn-flat" })
                @Html.ActionLink("Registrarse", "Register", "User", null, new { @class = "white-text waves-effect waves-teal btn-flat" })
            } else
            {
                <a class="white-text waves-effect waves-teal btn-flat">Hola, <strong>@Session["UserNombre"]</strong></a>
                @Html.ActionLink("Logout", "Logout", "Ingresar",null, new { @class = "white-text waves-effect waves-teal btn-flat" })
            }

        </div>
</div>

    @RenderBody()


    @Scripts.Render("~/bundles/ui-libs")
    @Scripts.Render("~/bundles/Views")
    @RenderSection("scripts", required: false)
</body>
</html>

TpIntegrador/Views/Shared/PropuestasLayout.cshtml
@{
    Layout = "~/Views/Shared/BaseLayout.cshtml";
}

<nav class="teal">
    <div class="container nav-wrapper">
        <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
            <li>@Html.ActionLink("Crear propuesta", "AgregarPropuesta", "Propuestas")</li>
            <li>@Html.ActionLink("Mi perfil", "Index", "Perfil")</li>
            <li>@Html.ActionLink("Acerca de", "Acerca-de", "Home")</li>
            <li>@Html.ActionLink("Denuncias", "Complaints", "Admin")</li>
            <li>@Html.ActionLink("Mis Donaciones", "MisDonaciones", "Donaciones")</li>
            @if ((int)Session["User"] == 1)
            {
                <li>@Html.ActionLink("Denuncias", "Complaints", "Admin")</li>
            }
        </ul>
    </div>
</nav>

<main>
    @RenderBody()
</main>


@Html.Partial("pv_Footer")

TpIntegrador/Views/Shared/pv_Footer.cshtml
<footer class="page-footer teal top-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Ayudando al projimo</h5>
                <p class="grey-text text-lighten-4">La primera plataforma de financiamiento colectivo (crowdfunding) dedicada para entidades sin fines de lucro.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Integrantes - Grupo 8</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3">Bragazzi, Julián</a></li>
                    <li><a class="grey-text text-lighten-3">Falon, Gabriel</a></li>
                    <li><a class="grey-text text-lighten-3">Hiroma, Fernando</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Programación Web 3 20192C © 2019 
        </div>
    </div>
</footer>