TpIntegrador/Controllers/DonacionesController.cs
using AyudandoAlProjimo.Data;
using AyudandoAlProjimo.Data.ViewModels;
using AyudandoAlProjimo.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TpIntegrador.Filters;
using TpIntegrador.Utilities;

namespace TpIntegrador.Controllers
{
    public class DonacionesController : Controller
    {
        private ProposalService ProposalService = new ProposalService();

        [CheckSession]
        public ActionResult Index(int id)
        {
            var p = ProposalService.BuscarPorId(id);

            switch (p.TipoDonacion)
            {
                case (int)TipoPropuestaEnum.Monetaria:
                    return Redirect("/Donaciones/DonarMonetario/" + id);
                case (int)TipoPropuestaEnum.Insumos:
                    return Redirect("/Donaciones/DonarInsumos/" + id);
                case (int)TipoPropuestaEnum.HorasTrabajo:
                    return Redirect("/Donaciones/DonarHoras/" + id);
            }

            return View();
        }

        [CheckSession]
        public ActionResult DonarInsumos(int id)
        {
            RealizarDonacionInsumosViewModel m = new RealizarDonacionInsumosViewModel();
            m.Propuesta = ProposalService.BuscarPorId(id);
            m.Formulario = new RealizarDonacionInsumosFormulario();
            m.Formulario.Insumos = new List<InsumosViewModel>();
            foreach (var item in m.Propuesta.PropuestasDonacionesInsumos)
            {
                m.Formulario.Insumos.Add(new InsumosViewModel() { Id = item.IdPropuestaDonacionInsumo, Cantidad = 0, Nombre = item.Nombre });
            }

            return View(m);
        }

        [CheckSession]
        public ActionResult DonarMonetario(int id)
        {
            RealizarDonacionMonetariaViewModel m = new RealizarDonacionMonetariaViewModel();
            m.Formulario = new RealizarDonacionMonetariaFormulario();
            m.Propuesta = ProposalService.BuscarPorId(id);

            return View(m);
        }

        [CheckSession]
        public ActionResult DonarHoras(int id)
        {
            RealizarDonacionHorasViewModel m = new RealizarDonacionHorasViewModel();
            m.Formulario = new RealizarDonacionHorasFormulario();
            m.Propuesta = ProposalService.BuscarPorId(id);

            return View(m);
        }

        [CheckSession]
        public ActionResult MisDonaciones()
        {
            ViewBag.SessionID = Session["ID"];
            return View();
        }

        [HttpPost]
        public ActionResult DonarMonetario(RealizarDonacionMonetariaViewModel m)
        {
            int id = Int32.Parse(RouteData.Values["id"].ToString());
            m.Propuesta = ProposalService.BuscarPorId(id);

            if (!ModelState.IsValid) return View(m);

            var name = m.Propuesta.Nombre + "-" + Session["ID"];
            m.Formulario.ArchivoTransferencia = GetPathForPhoto(name);

            ProposalService.AgregarDonacionMonetaria(m.Formulario, (int)Session["ID"], id);

            return Redirect("/Home/Index");
        }

        [HttpPost]
        public ActionResult DonarHoras(RealizarDonacionHorasViewModel m)
        {
            int id = Int32.Parse(RouteData.Values["id"].ToString());
            m.Propuesta = ProposalService.BuscarPorId(id);

            if (!ModelState.IsValid) return View(m);

            ProposalService.AgregarDonacionHoras(m.Formulario, (int)Session["ID"], id);

            return Redirect("/Home/Index");
        }

        [HttpPost]
        public ActionResult DonarInsumos(RealizarDonacionInsumosViewModel m)
        {
            int id = Int32.Parse(RouteData.Values["id"].ToString());
            m.Propuesta = ProposalService.BuscarPorId(id);

            if (!ModelState.IsValid) return View(m);

            ProposalService.AgregarDonacionInsumos(m.Formulario, (int)Session["ID"], id);

            return Redirect("/Home/Index");
        }

        private string GetPathForPhoto(string name)
        {
            return ImagenesUtility.Guardar(Request.Files[0], name + "-FOTO");
        }
    }
}

TpIntegrador/Controllers/PropuestasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AyudandoAlProjimo.Data;
using AyudandoAlProjimo.Data.ViewModels;
using AyudandoAlProjimo.Services;
using TpIntegrador.Filters;
using TpIntegrador.Utilities;

namespace TpIntegrador.Controllers
{
    public class PropuestasController : Controller
    {
        private ProposalService ProposalService = new ProposalService();
        private UserService UserService = new UserService();

        [CheckSession]
        public ActionResult AgregarPropuesta()
        {
            return View();
        }

        [CheckSession]
        public ActionResult AgregarPropuestaMonetaria()
        {
            AgregarPropuestaMonetariaViewModel p = new AgregarPropuestaMonetariaViewModel();

            p.TipoDonacion = TipoPropuestaEnum.Monetaria;

            return View(p);
        }

        [CheckSession]
        public ActionResult AgregarPropuestaInsumos()
        {
            AgregarPropuestaInsumosViewModel p = new AgregarPropuestaInsumosViewModel();

            p.TipoDonacion = TipoPropuestaEnum.Insumos;

            return View(p);
        }

        [CheckSession]
        public ActionResult AgregarPropuestaHoraTrabajo()
        {
            AgregarPropuestaHoraTrabajoViewModel p = new AgregarPropuestaHoraTrabajoViewModel();

            p.TipoDonacion = TipoPropuestaEnum.HorasTrabajo;

            return View(p);
        }

        [HttpPost]
        public ActionResult AgregarPropuestaMonetaria(AgregarPropuestaMonetariaViewModel p)
        {
            if (!ModelState.IsValid) return View(p);

            var user = UserService.TraerPerfilDelUsuario((int)Session["ID"]);
            var error = ProposalService.ValidateBeforeCreate(user);

            if (error != ErrorCodeAddProposalEnum.None)
            {
                ViewBag.Error = error;

                return View(p);
            }

            p.Foto = GetPathForPhoto(user.UserName + p.Nombre);

            ProposalService.AgregarPropuestaMonetaria(p, user);

            return Redirect("/Home/Index");
        }

        [HttpPost]
        public ActionResult AgregarPropuestaHoraTrabajo(AgregarPropuestaHoraTrabajoViewModel p)
        {
            if (!ModelState.IsValid) return View(p);

            var user = UserService.TraerPerfilDelUsuario((int)Session["ID"]);
            var error = ProposalService.ValidateBeforeCreate(user);

            if (error != ErrorCodeAddProposalEnum.None)
            {
                ViewBag.Error = error;

                return View(p);
            }

            p.Foto = GetPathForPhoto(user.UserName + p.Nombre);

            ProposalService.AgregarPropuestaHoraTrabajo(p, user);

            return Redirect("/Home/Index");
        }

        [HttpPost]
        public ActionResult AgregarPropuestaInsumos(AgregarPropuestaInsumosViewModel p)
        {
            if (!ModelState.IsValid) return View(p);

            var user = UserService.TraerPerfilDelUsuario((int)Session["ID"]);
            var error = ProposalService.ValidateBeforeCreate(user);

            if (error != ErrorCodeAddProposalEnum.None)
            {
                ViewBag.Error = error;

                return View(p);
            }

            p.Foto = GetPathForPhoto(user.UserName + p.Nombre);

            ProposalService.AgregarPropuestaInsumos(p, user);

            return Redirect("/Home/Index");
        }

        [HttpGet]
        public ActionResult VerDetalles(int id)
        {
            return View(ProposalService.VerPropuestaYDonaciones(id));
        }
        [HttpGet]
        public ActionResult ModificarPropuesta(int id)
        {
            return View(ProposalService.VerPropuestaYDonaciones(id));
        }
        [HttpPost]
        public ActionResult ModificarPropuesta(PropuestaViewModel pvm)
        {
            if (ModelState.IsValid)
            {
                if (pvm.Propuesta.Foto != null)
                {
                    pvm.Propuesta.Foto = GetPathForPhoto(pvm.Propuesta.Foto +pvm.Propuesta.Nombre);
                }
                ProposalService.ModificarPropuestaBase(pvm);
                return Redirect("/Propuestas/VerDetalles/" + pvm.Propuesta.IdPropuesta);
            }
            return View(pvm);
        }
        private bool isValidUserSession()
        {
            return Session["ID"] != null && UserService.TraerPerfilDelUsuario((int)Session["ID"]) != null;
        }

        private string GetPathForPhoto(AgregarPropuestaBase p)
        {
            return ImagenesUtility.Guardar(Request.Files[0], p.Nombre + "-FOTO");
        }

        [CheckSession]
        [HttpGet]
        public ActionResult Valoracion(int id, string valor)
        {
            ProposalService.Valorar(id, (int)Session["ID"], valor);
            return Redirect("/Home/Index");
        }

        private string GetPathForPhoto(string name)
        {
            return ImagenesUtility.Guardar(Request.Files[0], name + "-FOTO");
        }
    }
}

TpIntegrador/Views/Propuestas/AgregarPropuesta.cshtml
@model AyudandoAlProjimo.Data.ViewModels.AgregarPropuestaMonetariaViewModel
@{
    Layout = "~/Views/Shared/PropuestasLayout.cshtml";
    ViewBag.Title = "Nueva propuesta";
}

<div class="container">
    <div class="card margin-top-bottom-50">
        <div class="card-content">
            <div class="row no-margin">

                <h5>¿Que tipo de donacion desea que tenga su propuesta?</h5>

                <ul>
                    <li>@Html.ActionLink("Monetaria", "AgregarPropuestaMonetaria", "Propuestas", null, new { @class = "waves-effect waves-teal btn-flat" })</li>
                    <li>@Html.ActionLink("Horas de trabajo", "AgregarPropuestaHoraTrabajo", "Propuestas", null, new { @class = "waves-effect waves-teal btn-flat" })</li>
                    <li>@Html.ActionLink("Insumos", "AgregarPropuestaInsumos", "Propuestas", null, new { @class = "waves-effect waves-teal btn-flat" })</li>
                </ul>

            </div>
        </div>
    </div>
</div>

TpIntegrador/Views/Propuestas/AgregarPropuestaHoraTrabajo.cshtml
@model AyudandoAlProjimo.Data.ViewModels.AgregarPropuestaHoraTrabajoViewModel
@{
    Layout = "~/Views/Shared/PropuestasLayout.cshtml";
    ViewBag.Title = "Nueva propuesta";
}

@using (Html.BeginForm("AgregarPropuestaHoraTrabajo", "Propuestas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="container">
        @if (ViewBag.Error != null)
        {
            <div class="card red">
                <div class="card-content white-text">
                    @if (ViewBag.Error == AyudandoAlProjimo.Data.ErrorCodeAddProposalEnum.InvalidProfile)
                    {
                        <p>Aún no tienes completado todos los datos en tu perfil, haz click aqui para completarlos. @Html.ActionLink("Mi Perfil", "", "", null, new { @class = "white-text waves-effect waves-teal btn-flat" })</p>
                    }

                    @if (ViewBag.Error == AyudandoAlProjimo.Data.ErrorCodeAddProposalEnum.InvalidProposalCount)
                    {
                        <p>Actualmente tiene mas de 3 propuestas activas</p>
                    }
                </div>
            </div>
        }
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">account_circle</i>
                        @Html.EditorFor(x => x.Nombre, new { htmlAttributes = new { @class = "validate", @id = "namePropuesta", @required = true } })
                        <label for="namePropuesta">Nombre de la propuesta</label>
                        @Html.ValidationMessageFor(x => x.Nombre, "", new { @class = "text-danger" })
                    </div>

                    <div class="input-field col s12">
                        <i class="material-icons prefix">edit</i>
                        @Html.TextAreaFor(x => x.Descripcion, new { @class = "validate materialize-textarea", @id = "description", @required = true })
                        <label for="description">Descripcion</label>
                        @Html.ValidationMessageFor(x => x.Descripcion, "", new { @class = "text-danger" })
                    </div>

                    <div class="input-field col s6">
                        <i class="material-icons prefix">date_range</i>
                        @Html.EditorFor(x => x.FechaFin, new { htmlAttributes = new { @class = "validate", @id = "endDate", @required = true } })
                        <label for="endDate" class="active">Fecha fin (dd/mm/aaaa)</label>
                        @Html.ValidationMessageFor(x => x.FechaFin, "", new { @class = "text-danger" })
                    </div>

                    <div class="input-field col s6">
                        <i class="material-icons prefix">phone</i>
                        @Html.EditorFor(x => x.TelefonoContacto, new { htmlAttributes = new { @class = "validate", @id = "phone", @required = true } })
                        <label for="phone">Telefono de contacto</label>
                        @Html.ValidationMessageFor(x => x.TelefonoContacto, "", new { @class = "text-danger" })
                    </div>

                    <div class="input-field col s6">
                        <i class="material-icons prefix">timer</i>
                        @Html.EditorFor(x => x.CantidadHoras, new { htmlAttributes = new { @class = "validate", @id = "hourstime" } })
                        <label for="hourstime">Cantidad de horas</label>
                    </div>

                    <div class="input-field col s6">
                        <i class="material-icons prefix">wc</i>
                        @Html.DropDownListFor(x => x.Profesion,
                            new SelectList(new[] {
                                new { ID = "Albañil", Name = "Albañil" },
                                new { ID = "Plomero", Name = "Plomero" },
                                new { ID = "Electricista", Name = "Electricista" },
                                new { ID = "Abogado", Name = "Abogado" },
                                new { ID = "Contador", Name = "Contador" },
                                new { ID = "Trabajador Social", Name = "Trabajador Social" },
                                new { ID = "Psicologa", Name = "Psicologa" },
                                new { ID = "Psicopedagoga", Name = "Psicopedagoga" },
                                new { ID = "Cocinero", Name = "Cocinero" },
                                new { ID = "Otro", Name = "Otro" },
                            }, "ID", "Name", 1)
                            , new { @class = "with-gap", @id = "DonationType" })
                        <label for="moneyDestination">Profesion</label>
                    </div>


                    @for (int i = 0; i < 2; i++)
                    {
                        <div class="input-field col s6">
                            <i class="material-icons prefix">account_circle</i>
                            @Html.EditorFor(x => x.Referencias[i].Nombre, new { htmlAttributes = new { @class = "validate", @id = "namePropuesta", @required = true } })
                            <label for="namePropuesta">Nombre del referente</label>
                            @Html.ValidationMessageFor(x => x.Nombre, "", new { @class = "text-danger" })
                        </div>

                        <div class="input-field col s6">
                            <i class="material-icons prefix">phone</i>
                            @Html.EditorFor(x => x.Referencias[i].Telefono, new { htmlAttributes = new { @class = "validate", @id = "photo", @required = true } })
                            <label for="photo">Telefono del referente</label>
                            @Html.ValidationMessageFor(x => x.TelefonoContacto, "", new { @class = "text-danger" })
                        </div>
                    }

                    <input type="file" name="Foto" accept="image/*" />
                    <p>
                        @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                    </p>

                </div>

                <button class="btn waves-effect waves-light" type="submit" name="action">
                    Enviar
                    <i class="material-icons right">send</i>
                </button>


            </div>
        </div>
    </div>
}

TpIntegrador/Views/Propuestas/AgregarPropuestaInsumos.cshtml
@model AyudandoAlProjimo.Data.ViewModels.AgregarPropuestaInsumosViewModel
@{
    Layout = "~/Views/Shared/PropuestasLayout.cshtml";
    ViewBag.Title = "Nueva propuesta";
}

@using (Html.BeginForm("AgregarPropuestaInsumos", "Propuestas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="container">
        @if (ViewBag.Error != null)
        {
            <div class="card red">
                <div class="card-content white-text">
                    @if (ViewBag.Error == AyudandoAlProjimo.Data.ErrorCodeAddProposalEnum.InvalidProfile)
                    {
                        <p>Aún no tienes completado todos los datos en tu perfil, haz click aqui para completarlos. @Html.ActionLink("Mi Perfil", "", "", null, new { @class = "white-text waves-effect waves-teal btn-flat" })</p>
                    }

                    @if (ViewBag.Error == AyudandoAlProjimo.Data.ErrorCodeAddProposalEnum.InvalidProposalCount)
                    {
                        <p>Actualmente tiene mas de 3 propuestas activas</p>
                    }
                </div>
            </div>
        }
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">account_circle</i>
                        @Html.EditorFor(x => x.Nombre, new { htmlAttributes = new { @class = "validate", @id = "namePropuesta", @required = true } })
                        <label for="namePropuesta">Nombre de la propuesta</label>
                        @Html.ValidationMessageFor(x => x.Nombre, "", new { @class = "text-danger" })
                    </div>

                    <div class="input-field col s12">
                        <i class="material-icons prefix">edit</i>
                        @Html.TextAreaFor(x => x.Descripcion, new { @class = "validate materialize-textarea", @id = "description", @required = true })
                        <label for="description">Descripcion</label>
                        @Html.ValidationMessageFor(x => x.Descripcion, "", new { @class = "text-danger" })
                    </div>

                    <div class="input-field col s6">
                        <i class="material-icons prefix">date_range</i>
                        @Html.EditorFor(x => x.FechaFin, new { htmlAttributes = new { @class = "validate", @id = "endDate", @required = true } })
                        <label for="endDate" class="active">Fecha fin (dd/mm/aaaa)</label>
                        @Html.ValidationMessageFor(x => x.FechaFin, "", new { @class = "text-danger" })
                    </div>

                    <div class="input-field col s6">
                        <i class="material-icons prefix">phone</i>
                        @Html.EditorFor(x => x.TelefonoContacto, new { htmlAttributes = new { @class = "validate", @id = "phone", @required = true } })
                        <label for="phone">Telefono de contacto</label>
                        @Html.ValidationMessageFor(x => x.TelefonoContacto, "", new { @class = "text-danger" })
                    </div>

                    <div class="col s12">
                        <p>Insumos:</p>
                    </div>

                    <div id="container-insumos">
                        <div id="insumo-0">
                            <div class="input-field col s6">
                                <i class="material-icons prefix">build</i>
                                @Html.EditorFor(x => x.Insumos[0].Nombre, new { htmlAttributes = new { @class = "validate" } })
                                <label for="moneyDestination">Nombre</label>
                                @Html.ValidationMessageFor(x => x.Insumos[0].Nombre, "", new { @class = "text-danger" })
                            </div>

                            <div class="input-field col s6">
                                <i class="material-icons prefix">poll</i>
                                @Html.EditorFor(x => x.Insumos[0].Cantidad, new { htmlAttributes = new { @class = "validate" } })
                                <label>Cantidad</label>
                                @Html.ValidationMessageFor(x => x.Insumos[0].Cantidad, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>


                    <div class="col s12">
                        <div class="right">
                            <button class="btn waves-effect waves-light" type="button" id="btnAddInsumo">
                                Agregar un nuevo insumo
                                <i class="material-icons right">plus_one</i>
                            </button>
                        </div>
                    </div>

                    @for (int i = 0; i < 2; i++)
                    {
                        <div class="input-field col s6">
                            <i class="material-icons prefix">account_circle</i>
                            @Html.EditorFor(x => x.Referencias[i].Nombre, new { htmlAttributes = new { @class = "validate", @id = "namePropuesta", @required = true } })
                            <label for="namePropuesta">Nombre del referente</label>
                            @Html.ValidationMessageFor(x => x.Nombre, "", new { @class = "text-danger" })
                        </div>

                        <div class="input-field col s6">
                            <i class="material-icons prefix">phone</i>
                            @Html.EditorFor(x => x.Referencias[i].Telefono, new { htmlAttributes = new { @class = "validate", @id = "photo", @required = true } })
                            <label for="photo">Telefono del referente</label>
                            @Html.ValidationMessageFor(x => x.TelefonoContacto, "", new { @class = "text-danger" })
                        </div>
                    }

                    <input type="file" name="Foto" accept="image/*" />
                    <p>
                        @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                    </p>

                </div>

                <button class="btn waves-effect waves-light" type="submit" name="action">
                    Enviar
                    <i class="material-icons right">send</i>
                </button>


            </div>
        </div>
    </div>
}

TpIntegrador/Views/Propuestas/DonarMonetario.cshtml
@model AyudandoAlProjimo.Data.ViewModels.RealizarDonacionMonetariaViewModel
@{
    Layout = "~/Views/Shared/PropuestasLayout.cshtml";
    ViewBag.Title = "Nueva propuesta";
}

<div class="container">
    <div class="card margin-top-bottom-50">
        <div class="card-content">
            <div class="row no-margin">
                <h2 class="title-propuesta no-margin">Donación para @Model.Propuesta.Nombre</h2>

                <p class="title-recaudado margin-bottom-20">
                    CBU: <strong>@Model.Propuesta.PropuestasDonacionesMonetarias.FirstOrDefault().CBU</strong>
                </p>

                <div class="margin-bottom-20">
                    <ul class="tabla-objetivos">
                        <li>
                            <p>
                                <strong>$@(Model.Propuesta.PropuestasDonacionesMonetarias.Count > 0 ? Model.Propuesta.PropuestasDonacionesMonetarias.FirstOrDefault().Dinero : 0)</strong>
                            </p>
                            <span class="info-text">Objetivo</span>
                        </li>
                        <li>
                            <p>
                                <strong>@(Model.Propuesta.PropuestasDonacionesMonetarias.Count > 0 ? Model.Propuesta.PropuestasDonacionesMonetarias.FirstOrDefault().DonacionesMonetarias.Sum(x => x.Dinero) : 0)</strong>
                            </p>
                            <span class="info-text">Recaudado</span>
                        </li>
                        <li>
                            <p><strong>@(Math.Round((Model.Propuesta.FechaFin - DateTime.Now).TotalDays))</strong></p>
                            <span class="info-text">Días restantes</span>
                        </li>
                    </ul>
                </div>

                @using (Html.BeginForm("DonarMonetario", "Propuestas", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="row margin-bottom-20">
                        <div class="input-field col s6">
                            <i class="material-icons prefix">attach_money</i>
                            @Html.EditorFor(model => model.Formulario.Dinero, new { htmlAttributes = new { @class = "validate" } })
                            <label>Usuario</label>
                            @Html.ValidationMessageFor(model => model.Formulario.Dinero, "", new { @class = "text-danger" })
                        </div>

                        <div class="input-field col s6">
                            <input type="file" name="Formulario.ArchivoTransferencia" accept="image/*" />
                            <p>
                                @Html.ValidationMessageFor(model => model.Formulario.ArchivoTransferencia, "", new { @class = "text-danger" })
                            </p>
                        </div>

                        <div class="right">
                            <button class="btn waves-effect waves-light" type="submit" name="action">Enviar<i class="material-icons right">edit</i></button>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

TpIntegrador/Views/Propuestas/VerDetalles.cshtml
@model AyudandoAlProjimo.Data.ViewModels.PropuestaViewModel

@{
    Layout = Session["ID"] == null ? "~/Views/Shared/AnonimoLayout.cshtml" : "~/Views/Shared/PropuestasLayout.cshtml";
    ViewBag.Title = Model.Propuesta.Nombre;
}

<div class="container">
    <div class="card margin-top-bottom-50">
        <div class="card-content">
            <div class="row">
                <div class="col s6">
                    <img src="@Model.Propuesta.Foto" style="max-width: 100%;" />
                </div>

                <div class="col s6">
                    <h2 class="title-propuesta no-margin">@Model.Propuesta.Nombre</h2>
                    <p class="title-autor-propuesta">Por: @Model.UsuarioCreador.Nombre @Model.UsuarioCreador.Apellido (@Model.UsuarioCreador.Email), Fecha: @Model.Propuesta.FechaCreacion</p>

                    <p class="title-recaudado margin-bottom-20">
                        Valoracion: <strong>@Model.Propuesta.Valoracion</strong>
                    </p>

                    <div class="margin-bottom-20">
                        <p style="margin-bottom: 5px;" class="title-recaudado">Referentes:</p>
                        @foreach (var item in Model.Propuesta.PropuestasReferencias)
                        {
                            <p class="d-flex"><i style="margin-right: 10px;" class="material-icons prefix">account_circle</i>@item.Nombre (@item.Telefono)</p>
                        }
                    </div>

                    @{
                        switch (Model.Propuesta.TipoDonacion)
                        {
                            case (int)AyudandoAlProjimo.Data.TipoPropuestaEnum.Monetaria:
                                Html.RenderPartial("_DetalleMonetaria");
                                break;
                            case (int)AyudandoAlProjimo.Data.TipoPropuestaEnum.HorasTrabajo:
                                Html.RenderPartial("_DetalleHoras");
                                break;
                            case (int)AyudandoAlProjimo.Data.TipoPropuestaEnum.Insumos:
                                Html.RenderPartial("_DetalleInsumos");
                                break;
                        }
                    }

                    <div class="title-recaudado">
                        Porcentaje realizacion: <strong>@Model.PorcentajeRealizacion%</strong>
                        <div class="progress">
                            <div class="determinate" style="width: @Model.PorcentajeRealizacion%"></div>
                        </div>
                    </div>


                    @if (TempData["Mensaje" + Model.Propuesta.IdPropuesta] != null)
                    {
                        <div>
                            <p>@TempData["Mensaje" + Model.Propuesta.IdPropuesta]</p>
                        </div>
                    }

                    @Html.ActionLink("Apoyar al proyecto", "Index", "Donaciones", new { id = Model.Propuesta.IdPropuesta }, new { @class = "btn waves-effect waves-light" })

                    <a class="btn waves-effect waves-light" href="@Url.Action("Valoracion", "Propuestas", new { id = Model.Propuesta.IdPropuesta, valor = "Like" } )">
                        <i class="material-icons left">thumb_up_alt</i>
                        Me gusta
                    </a>

                    <a class="btn waves-effect waves-light" href="@Url.Action("Valoracion", "Propuestas", new { id = Model.Propuesta.IdPropuesta, valor = "Dislike" } )">
                        <i class="tiny material-icons left">thumb_down_alt</i>
                        No me gusta
                    </a>

                    <p style="margin-top: 10px;">
                        <a href=@Url.Action("Denunciar","User", new { id=Model.Propuesta.IdPropuesta}) class="btn waves-effect waves-light red">
                            Denunciar
                        </a>
                    </p>
                </div>

            </div>
            <div class="row">
                <div class="col s12">
                    <h2 class="title-propuesta no-margin">Más información sobre el proyecto</h2>
                    <p>@Model.Propuesta.Descripcion</p>
                </div>
            </div>
        </div>
    </div>
</div>

TpIntegrador/Views/Propuestas/_DetalleHoras.cshtml
@model AyudandoAlProjimo.Data.ViewModels.PropuestaViewModel

<ul class="tabla-objetivos">
    <li>
        <p><strong>@Model.Propuesta.PropuestasDonacionesHorasTrabajo.FirstOrDefault().CantidadHoras</strong></p>
        <span class="info-text">Objetivo (Horas)</span>
    </li>
    <li>
        <p><strong>@Model.Propuesta.PropuestasDonacionesHorasTrabajo.FirstOrDefault().Profesion</strong></p>
        <span class="info-text">Profesion sugerida</span>
    </li>
    <li>
        <p><strong>@Model.DonacionesHorasTrabajo.Sum(x => x.Cantidad)</strong></p>
        <span class="info-text">Recaudado (Horas)</span>
    </li>
    <li>
        <p><strong>@(Math.Round((Model.Propuesta.FechaFin - DateTime.Now).TotalDays))</strong></p>
        <span class="info-text">Días restantes</span>
    </li>
</ul>